common/common.pro
needed because common is dependent on the Settings class
from kdwsdl2cpp.
=> common/common.pro - hack to compile against kdwsdl2cpp

common/fileprovider.cpp, common/fileprovider.h, schema/parser.cpp, schema/parser.h
Fix #4: removing depencency to the KDSOAP's Settings class by passingthe settings data through parameters to the FileProvider. (And moving the loaded SSL configuration global.)
=> Fix #4: removing depencency to the KDSOAP's Settings class

code_generation/class.cpp, code_generation/class.h, code_generation/code_generation.pro, code_generation/include.cpp, code_generation/include.h, code_generation/printer.cpp
In a project using libkode I needed to add includes to my generated classes with relative paths (with `#include "foobar.h"` format).
This PR adds the ability to specify the include mode through the Class class. 
The include type is specified by an additional optional argument and by default it set to Global (what is the current upstream behaviour.)
=> [code_generation]Add ability to add realitve includes to classes

common/fileprovider.cpp, common/fileprovider.h, schema/parser.cpp, schema/parser.h
E.g. KDSoap's kdwsdl2cpp will provide copies of soap-encoding v1.1 and
v1.2, and soap-envelope. This will avoid having to download those from
the internet when they are used in an <import> clause, making it
possible to build unittests on CIs without internet access.
See https://github.com/KDAB/KDSoap/issues/203
=> Add Parser::setLocalSchemas() to provide local copies of common schemas

code_generation/license.cpp, code_generation/license.h
Added new static methods getLicenseNameByString(), getLicenseNameByEnum(), getSupportedLicenses().
These methods intended for easing license management in kxml_compiler.
=> Added enumeration features to KODE::License::Type

schema/parser.cpp
urlForLocation() incorrectly build filepath as "/file.xsd" instead "./file.xsd" if file placed in relative path.
To avoid failing downloading via FileProvider, return url are converted to URL form with schema (like "file:./file.xsd").
Fixes https://github.com/cornelius/kode/issues/55
=> Fix broken local include for XSD

code_generation/printer.cpp
Fix deprecated QList::toSet and QSet::toList calls.
=> Fix deprecated QList::toSet and QSet::toList calls

common/fileprovider.cpp
Enable no-less-safe redirect policy to allow file downloads that require to follow a redirect.
Currently schema (and really all file downloads) will return wrong results if the target server uses a redirect to the final file.
=> Allow file downloads to follow redirects.

code_generation/printer.cpp
Class::set/isQGadget have been there for a while, however the Printer class it got ignored.
=> Generate Q_GADGET macro if the Class::isQGadget is true

.github/workflows/build.yml
The CI builds failed because the set-env was deprecated in the Github workflows.
See:
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
https://github.com/jurplel/install-qt-action/issues/64
I have upgraded the jurplel/install-qt-action to the latest version, where this issue is fixed.
=> Update the github build action Qt installing step

code_generation/printer.cpp
Title says almost all: now it is going to be possible to generate headers having #pragma once based include.
=> Implement #pragma once guard generation to headers (fixed #29)

code_generation/enum.cpp, code_generation/enum.h, code_generation/printer.cpp
The enum declarations are indented to newlines. 
The enum class now generates the declarations through a Code object (which ease the indentation handling).
The Enum::declaration does not used elsewhere so we might remove that. KDSoap and KODE does not use it directly only through the Printer, which got modified in this commit to use the new Code object based approach.
=> Add ability to generate enums with Q_ENUM macros

code_generation/enum.cpp, code_generation/enum.h
As @dfaure-kdab suggested in the #32 discussion removing the unused Enum::declaration function.
=> Removed Enum::declaration method

schema/parser.cpp
This macro is available since Qt 5.4.
=> Silence parser debug output by default

schema/attribute.cpp, schema/attribute.h, schema/attributegroup.cpp, schema/attributegroup.h, schema/complextype.cpp, schema/complextype.h, schema/element.cpp, schema/element.h, schema/group.cpp, schema/group.h, schema/parser.cpp, schema/xmlelement.cpp, schema/xmlelement.h, schema/xsdtype.cpp, schema/xsdtype.h
Manual merge of pull request from Holger Kaelberer in KDSoap since
the code moved to this repository.
So far, for complexTypes nested in elements with the same name a
single C++ class has been created. This is wrong in cases where
multiple elements with the same name contain complexTypes of different
structure because different classes should be created
Beside, new types for structurally different complexTypes only.
=> kdwsdl2cpp: Avoid potential type collisions in nested complexTypes

CMakeLists.txt, autotests/CMakeLists.txt, autotests/tst_xmlelement.cpp, schema/CMakeLists.txt, schema/xmlelement.cpp, schema/xmlelement.h
With unittest.
If we agree on the way to do it, it can then be done just the same
in all other classes.
Initially prompted by a Coverity report suggesting that move operations
are missing.
=> Implement move support in XmlElement, based on a swap method.

autotests/CMakeLists.txt, autotests/tst_element.cpp, autotests/tst_group.cpp, schema/annotation.cpp, schema/annotation.h, schema/attribute.cpp, schema/attribute.h, schema/attributegroup.cpp, schema/attributegroup.h, schema/complextype.cpp, schema/complextype.h, schema/compositor.cpp, schema/compositor.h, schema/element.cpp, schema/element.h, schema/group.cpp, schema/group.h, schema/parser.cpp, schema/parser.h, schema/simpletype.cpp, schema/simpletype.h, schema/types.cpp, schema/types.h, schema/xmlelement.cpp, schema/xmlelement.h, schema/xsdtype.cpp, schema/xsdtype.h
This partially reverts the previous commit in XmlElement to choose a
more optimal solution. The copy constructor is as before (instead of
calling a too-generic std::swap that will create more temporaries).
The move constructor was allocating needlessly, we just need to
grab the pointer of the other instance.
So instead this now uses unique_ptr to simplify the destructor and because
it gives us the move operations automatically.
Independently from move operations, this code review also spotted
a number of missing calls to base classes in the existing operator=.
Proved by unittests, and fixed.
=> Port all schema (XSD::) classes to unique_ptr and add move operations

code_generation/function.h, code_generation/printer.cpp
Hello @dfaure-kdab 
I needed to generate some code where the inherited functions were marked with final.
This change allowed me to do that.
BTW. are you aware further post function specifiers?
=> Add support for generating functions with final specifier

code_generation/class.cpp, code_generation/function.cpp, code_generation/function.h, code_generation/printer.cpp
Hi @dfaure-kdab 
As we discussed here:
https://github.com/KDAB/KDSoap/issues/206
I added a method for generating classes with explicit specifier.
I know it is not nice, but I included some "code cleanup" while I was poking around the code. Could you please review them as well?
I was wondering about setting a default true value for the isExplicit argument of the setExplicit method. What do you think about this one?
=> Add support for generating function declarations with explicit specifier

code_generation/printer.cpp
This was generating "class ;" without any class name, in KDSoap.
It's more correct to use isEmpty() rather than rely on isNull()
behaviour from QString::split() anyway.
=> Fix Qt 6.3 regression, QString null vs empty mixup.

schema/parser.cpp
The CI logs for KDSoap were huge because of one element not found in a unittest (possibly to the point of the Windows CI timing out)
=> Reduce verbosity on errors, with an env var as a switch

code_generation/enum.cpp, code_generation/enum.h
I use the libkode for C code generation and I needed to generate typedefs for enums.
It could came handy to others for similar purposes.
=> Add methods to being able to generate typedef-ed enums

schema/parser.cpp
libkode uses QDomDocument::setContent that was deprecated with Qt 6.8.
Use the non deprecated version that was added with Qt 6.5 if available.
With this change libkode can be compiled with QT_DISABLE_DEPRECATED_BEFORE=0x060900 / QT_DISABLE_DEPRECATED_UP_TO=0x060900
=> Replace function deprecated in Qt 6.8.
